default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_analytics: <%= ENV["GOOGLE_ANALYTICS"] %>
  smtp_address: <%= ENV["SMTP_ADDRESS"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
